### ISSUE TITLE
Non-functional in Firefox 34

### ISSUE THREAD

**Issue by Heptite** [their/amt#1]
It's behaving as if it's disabled or not even installed. Nothing shows up and it doesn't do anything. I can't even access its settings from a HIT page.

**Comment by davidshumway** [comment]
Hi Heptite
Thank you for the check in on this!
Indeed in Firefox 34 the tools button was not showing.
This is now fixed and version 1.0.9 for Firefox is now awaiting validation on addons.mozilla.org. It is in queue position 21 of 21. So it may take a few days before becoming active. See https://addons.mozilla.org/en-US/firefox/addon/toolsforamazonsmechanicaltu/versions/ for more details.
~Dave

**Comment by Heptite** [comment]
This fixes all the problems I was having, including it not resizing the job window or focusing CAPTCHA boxes. Thank you.
